services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
